### ISSUE TITLE
Current status and release?

### ISSUE THREAD

**Issue by minad** [qfpl/tasty-hedgehog#1]

**Comment by MichaelXavier** [comment]
Came here because I was about a minute away from writing my own version of this library. Any reason why this isn't on hackage? Anything you could use some help with?

**Comment by dalaing** [comment]
I kind of stalled a bit when I started my new job, although I hope to get
back to it soon. I can give you push access to what I have here if you
like.

Somehow I missed the github  notification when this issue was first
created, otherwise I would have added something about the status to the
Readme.

**Comment by MichaelXavier** [comment]
Sure! I was thinking about using hedgehog in new projects and I'm a tasty user. There looks like there's already quite a bit here. I think it probably makes sense to get a release up with an MVP even if it may be missing more advanced options or something. What do you see as missing for an MVP?

**Comment by dalaing** [comment]
I think it mostly needs to brought up to date with hedgehog - I first wrote this while hedgehog was moving very rapidly.

I'd also like to get the live progress updates working and the pretty output in there, but that can happen after this gets moving again.
