### ISSUE TITLE
Re-add tasty-hedgehog to Stackage

### ISSUE THREAD

**Issue by sjakobi** [qfpl/tasty-hedgehog#16]
That would be very convenient! :)

**Comment by decentral1se** [comment]
Eyo @sjakobi, I thought that went back in as of https://github.com/qfpl/tasty-hedgehog/issues/14.

However, upon looking in the `build-constraints.yaml`, I find it isn't there under anyone maintaining it!

Are package maintainers here up for that? I could potentially manage it ...

Perhaps we could organise some access for hackage uploads or something ...

**Comment by sjakobi** [comment]
Oh sorry, I hadn't seen #14.

In case the current maintainers aren't interested in listing `tasty-hedgehog` themselves, it would be great if you could do it @lwm! :+1:

**Comment by decentral1se** [comment]
Sure thing. I actually find that a lot of my maintenance issues for tasty-discover end up bringing me over here, so why not. I've opened up https://github.com/fpco/stackage/pull/3488. Please shout if someone else would prefer to manage it.

**Comment by sjakobi** [comment]
Thanks, @lwm!
