### ISSUE TITLE
Resolve bounds issue for GHC 8.4

### ISSUE THREAD

**Issue by decentral1se** [qfpl/tasty-hedgehog#18]
Please see https://github.com/fpco/stackage/pull/3488#issuecomment-379521018.

Will allow https://github.com/qfpl/tasty-hedgehog/issues/17 to happen.

**Comment by decentral1se** [comment]
Ah, I see this change has already landed!

https://github.com/qfpl/tasty-hedgehog/blob/master/tasty-hedgehog.cabal#L36

Hackage is timing out for me now but is there a latest release with this in?

**Comment by dalaing** [comment]
Yeah, the 0.2.0.0 release on Hackage has this in it.

**Comment by decentral1se** [comment]
Oh wait, it seems not:

> https://hackage.haskell.org/packages/search?terms=tasty%2Dhedgehog

Now that Hackage isn't timing out ...

We need a new release?

**Comment by dalaing** [comment]
I don't think so - the bounds on base for the 0.2.0.0 release on Hackage are `base (>=4.8 && <4.12)`, which would seem to resolve the linked issue.

**Comment by decentral1se** [comment]
~~Ah yes but not in the test suite. I'll make a PR.~~ Wait, you're right, it's done.

**Comment by decentral1se** [comment]
Ahhhh, it was a package revision ...

https://hackage.haskell.org/package/tasty-hedgehog-0.2.0.0/revisions/

I don't think Stackage pick those up? I'll open up a new submission and see ...
