### ISSUE TITLE
Unable to keep maintaining on Stackage

### ISSUE THREAD

**Issue by decentral1se** [qfpl/tasty-hedgehog#21]
FYI https://github.com/commercialhaskell/stackage/pull/3709

**Comment by MichaelXavier** [comment]
@lwm were there active issues with the latest resolvers? I'd be interested in taking over keeping this building on stackage. My only minor issue is that I don't have a nix setup and typically use stack with the project, so i may throw in a stack.yaml if i took over.

**Comment by decentral1se** [comment]
Hey @MichaelXavier, that'd be cool!

The only issues I had on the TODO were:

  - https://github.com/qfpl/tasty-hedgehog/issues/19
  - https://github.com/qfpl/tasty-hedgehog/issues/17

Good luck with it!

**Comment by MichaelXavier** [comment]
@lwm How much leeway do I have on this project? I can see we're doing that generated travis file and using nix. If I'm to maintain this package, I'd not want to try to retrofit that travis file to test against stackage and would instead opt for a stack-based test suite. These cache well and IME make it very easy to test against nightlies.
