### ISSUE TITLE
tasty-hedgehog-0.2.0.0 fails its test suite

### ISSUE THREAD

**Issue by peti** [qfpl/tasty-hedgehog#24]
Citing from https://hydra.nixos.org/build/88124541:

~~~
Running 1 test suites...
Test suite tasty-hedgehog-tests: RUNNING...
tasty-hedgehog tests
  reverse involutive:          OK
    OK
  badReverse involutive fails: PASS (unexpected)
    OK(unexpected success)

1 out of 2 tests failed (0.02s)
Test suite tasty-hedgehog-tests: FAIL
~~~

The complete build log as all information about the dependencies and compiler that used in that build.

**Comment by dalaing** [comment]
I'm unable to reproduce this with the latest tasty-hedgehog from github, using both `cabal test` and `cabal new-test` on NixOS, with the 18.09 and unstable versions of nixpkgs.

It looks like what Hydra is using and unstable are in pretty close agreement as far as dependencies go, so I'm not quite sure what is going on here.

**Comment by peti** [comment]
I re-restarted the failed build and this time the test suite suceeded. So whatever is causing the failure, it's obviously a transient phenomenon.

**Comment by dalaing** [comment]
Hmm, I think the way things currently are has the test at the mercy of the RNG, and  I'm pretty sure I can rework that test so that it is never involutive regardless of the RNG.  I'll take care of that on Monday when I get into work.

**Comment by peti** [comment]
I have just run into the same issue again. The test suite failed and broken some 150 builds that depend on tasty-hedgehog as a consequence. I'll disable the test suite entirely in Nix for now to avoid this kind of issue.

**Comment by gwils** [comment]
@peti Do you still experience this issue?

**Comment by peti** [comment]
No, I disabled the test suite in NixOS so that I could move forward.
