### ISSUE TITLE
Output of classify is not shown

### ISSUE THREAD

**Issue by dnadales** [qfpl/tasty-hedgehog#30]
When combining `hedgehog` and `tasty` the output of `classify` is not shown. See screenshot below:

The first output is what plain hedgehog shows (using `checkParallel`), and the second output is what `testProperty` shows (the classification is not shown):

![image](https://user-images.githubusercontent.com/175315/58005627-5ba33480-7ae6-11e9-90ee-b8cd80185a29.png)

**Comment by LightAndLight** [comment]
This is fixed with https://hackage.haskell.org/package/tasty-hedgehog-1.0.0.1.

Thanks for the issue :)

**Comment by dnadales** [comment]
Great! Thanks for this!
