### ISSUE TITLE
Tighten bounds on hedgehog

### ISSUE THREAD

**Issue by vmchale** [qfpl/tasty-hedgehog#34]
Hi!

tasty-hedgehog fails to build with hedgehog because `propertyTestLimit` is no longer exported by `Hedgehog.Internal.Property` as of hedgehog 1.0.2. Would it be possible to do a package revision to fix builds? 

Thanks!

**Comment by gwils** [comment]
Thanks for reporting this. I've revised versions 1.0.0.1 and 1.0.0.0.
