### ISSUE TITLE
Resolve tasty bounds issue to unblock affected stackage packages

### ISSUE THREAD

**Issue by decentral1se** [qfpl/tasty-hedgehog#4]
Following from [this diff over at Stackage](https://github.com/fpco/stackage/pull/3140/files), a number of packages have been blocked due to a bounds issue in `tasty-hedgehog`. I believe it was a result of the following bounds issue: https://github.com/fpco/stackage/issues/2995. I was able to verify that from https://packdeps.haskellers.com/feed?needle=tasty-hedgehog as well.

Also, I was able to reproduce a failing test case with:

```
$ stack unpack tasty-hedgehog && cd tasty-hedgehog
$ stack init --force
$ stack stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
```

Where the failing test case gives the following logs:

```
Progress: 33/34tasty-hedgehog tests
  reverse involutive:          OK (0.02s)
    OK
  badReverse involutive fails: FAIL (expected)
      ✗ badReverse involutive fails failed after 3 tests and 1 shrink.
      
           ┏━━ test/Main.hs ━━━
        14 ┃ test_involutive :: (MonadTest m, Eq a, Show a) => (a -> a) -> a -> m ()
        15 ┃ test_involutive f x =
        16 ┃   f (f x) === x
           ┃   ^^^^^^^^^^^^^
           ┃   │ Failed (- lhs =/= + rhs)
           ┃   │ - ""
           ┃   │ + "a"
        
           ┏━━ test/Main.hs ━━━
        29 ┃ prop_badReverse_involutive :: Property
        30 ┃ prop_badReverse_involutive =
        31 ┃   property $ do
        32 ┃     xs <- forAll genAlphaList
           ┃     │ "a"
        33 ┃     test_involutive badReverse xs
        
        This failure can be reproduced by running:
        > recheck (Size 2) (Seed 976115838098897482 (-4995829429754929789)) badReverse involutive fails
      
    Use '--hedgehog-replay "Size 2 Seed 976115838098897482 (-4995829429754929789)"' to reproduce.
    (expected failure)
```

**Comment by decentral1se** [comment]
Bump! Also see https://github.com/qfpl/tasty-hedgehog/issues/6#issuecomment-362094644. 👍

**Comment by dalaing** [comment]
I'm back in the office today (at last), so I pushed version 1.0.2 to hackage before I head off again tomorrow :) Hopefully I'll be a bit more responsive in the future when things are less hectic :/

**Comment by decentral1se** [comment]
Thanks @dalaing, no worries at all.

I've finally come back and got to https://github.com/fpco/stackage/pull/3313.

I'm gonna close off here and will raise again should anything else come up.

Thanks a lot!
