### ISSUE TITLE
Hackage version bounds confusion + lack of corresponding github release.

### ISSUE THREAD

**Issue by Unisay** [qfpl/tasty-hedgehog#44]
According to the [Hackage page for the package](https://hackage.haskell.org/package/tasty-hedgehog) I can use `hedgehog 1.0.4`  

![image](https://user-images.githubusercontent.com/1009751/103538165-00c67880-4e96-11eb-9255-cd88458cb3d9.png)

However,  if I [browse](https://hackage.haskell.org/package/tasty-hedgehog-1.0.0.2/src/) the [tar.gz package](https://hackage.haskell.org/package/tasty-hedgehog-1.0.0.2/tasty-hedgehog-1.0.0.2.tar.gz) contents on Hackage I can see different upper bound in the cabal file:
https://hackage.haskell.org/package/tasty-hedgehog-1.0.0.2/src/tasty-hedgehog.cabal

![image](https://user-images.githubusercontent.com/1009751/103538406-729ec200-4e96-11eb-8461-857ba777a47a.png)

Additionally, If I build my project that depends on `tasty-hedgehog-1.0.0.2` with stack I get the following upper bound:
```
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for tasty-hedgehog-1.0.0.2:
  tasty-1.4.0.2 from stack configuration does not match >=0.11 && <1.4  (latest matching version is 1.3.1)
```
Workaround for `stack.yaml` is to add and `extra-dep`:
```
  - github: qfpl/tasty-hedgehog 
    commit: 5956012cbb49c0d13db9ab0330e4140ee6702722
```

Please advise.

**Comment by gwils** [comment]
I believe this will be resolved in an upcoming stackage LTS. Until then, use `extra-dep` as you're doing.
