### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [qfpl/tasty-hedgehog#46]
I believe the `base` bounds need to relaxed. https://github.com/hedgehogqa/haskell-hedgehog/issues/416 needs to be resolved first though.

**Comment by gwils** [comment]
Cool, please ping me when the necessary hedgehog release happens and I can take care of this.

**Comment by RyanGlScott** [comment]
[`hedgehog-1.0.5`](http://hackage.haskell.org/package/hedgehog-1.0.5), which supports GHC 9.0.1, is now on Hackage.

**Comment by gwils** [comment]
Closed, but see #48
