### ISSUE TITLE
Use Github Actions CI instead of Travis, test GHC 9

### ISSUE THREAD

**Issue by gwils** [qfpl/tasty-hedgehog#48]
We want to replace the old travis build with a Github Actions build that tests the same GHC versions plus 9.0

**Comment by dhess** [comment]
Hi, thanks for tasty-hedgehog!

GHC 9.2.1 is out, but unsupported for this package because of the `base` bounds. Are there plans to update it?

**Comment by gwils** [comment]
Sure. We're admittedly not very good at maintaining these QFPL packages, and need nudging from time to time for things like this. Thanks!

**Comment by gwils** [comment]
I had a go at this. It looks like Hedgehog isn't ready for GHC-9.2 yet, so naturally this downstream package can't support 9.2 yet.
See https://github.com/hedgehogqa/haskell-hedgehog/pull/436

**Comment by dhess** [comment]
Yeah, we encountered similar. Thanks for looking into it and hopefully upstream will be fixed soon.
