### ISSUE TITLE
Deprecation message is really bad

### ISSUE THREAD

**Issue by Boarders** [qfpl/tasty-hedgehog#55]
The deprecation message when using `testProperty` is:
```
Deprecated: "testProperty will cause Hedgehog to provide incorrect instructions for re-checking 
properties"
```
This is really bad! It doesn't explain how to fix the issue or really why it is an issue, if it is as simple as using `testPropertyNamed` then the message should say that as otherwise I don't know how to fix the problem.

**Comment by mbg** [comment]
Yes, you should use `testPropertyNamed` instead. We can improve the deprecation message to mention this explicitly.

**Comment by lrworth** [comment]
Given that `testPropertyNamed n (PropertyName n) p` is equivalent to `testProperty n p`, `testPropertyNamed` must also suffer the incorrect instructions problem. What actually is that problem? What are the constraints on `propName`?
