### ISSUE TITLE
Undeprecate `testProperty`

### ISSUE THREAD

**Issue by ocharles** [qfpl/tasty-hedgehog#58]
Could I ask that `testProperty` not be deprecated? I understand that `testPropertyNamed` gives a better error message, but this mostly relies on a `Property` being a top-level function. There are many times where I generate a property based on in-scope variables, at which point I don't really have a top-level function (that is, whatever Hedgehog tells me to re-run is going to be wrong). `testProperty` feels like the right function to use here, even though the repro message is going to be wrong - I can live with that. I can of course turn off deprecations on my projects, but that's a big hammer.

**Comment by gwils** [comment]
This seems reasonable and I'm leaning towards doing it. Maybe just adding a comment to `testProperty` that `testPropertyNamed` is usually the one you want.
@mbg @andreabedini  What do you think of this?

**Comment by ocharles** [comment]
@gwils Yea, that sounds perfect to me.

**Comment by mbg** [comment]
I have just opened #59 which should address this. However, for completeness, I wanted to address the following:

> but this mostly relies on a `Property` being a top-level function

That's not really the case. The `PropertyName` argument to `testPropertyNamed` can be any string that represents an expression which reproduces the test case -- it doesn't necessarily have to be the name of a top-level definition. For example, if you generate a `TestTree` dynamically based on an in-scope variable, you could have something like:

```haskell
\x -> testPropertyNamed "some description" ("property $ ... " <> show x) $ property $ ... x
```

Maybe this helps you (or others) as well if you want more useful messages from Hedgehog than just `recheck ... <property>`.

**Comment by ocharles** [comment]
@mbg Good point, thanks for clarifying! (I would still like to just use `testProperty`, but your comment is a good clarification).

**Comment by ocharles** [comment]
Awesome, thank you @mbg and @gwils !
