### ISSUE TITLE
Add some CI for pull request builds

### ISSUE THREAD

**Issue by decentral1se** [qfpl/tasty-hedgehog#6]
I just submitted https://github.com/qfpl/tasty-hedgehog/pull/5 and it would probably be nice for maintainers to see if the build succeeds or not. I can start to add a Travis CI build if people are interested in that - or some other.

**Comment by MichaelXavier** [comment]
@dalaing Any opinions on how this should be done? I have set up tons of CI systems before but mostly for stack projects these days. Looks like this project uses nix and I don't really know how to get that working on travis.

**Comment by dalaing** [comment]
We've got CI for this setup for Hydra at the moment, [here](https://hydra.qfpl.io/jobset/tasty-hedgehog/tasty-hedgehog), although a) I need to add the plugin for GitHub PRs and b) we should probably consider using the multi-ghc-travis work to get it building and tested on more OSes.  I'll talk to someone on my team who has experience with that about making it happen.

I'm keen to get #5 into the fold, I've just been flat out.  I've merged it now, and if Hydra is happy I'll try to get a release out soon.

**Comment by dalaing** [comment]
Hmm, nixpkgs doesn't have the new version of tasty yet.  I'll talk to my coworker about getting all of this on travis as well.  Hopefully this will be sorted out sometime next week - I'm out of town for a few days, but that shouldn't slow things down too much.

I also found out that we'd already released a 0.1.0.1 version of the package, but something went wrong when I tried to push, so the github and hackage versions were a bit different.  I've bumped the version to 0.1.0.2 to reflect that.

**Comment by decentral1se** [comment]
Lovely job, thanks for taking this all under consideration @dalaing, @MichaelXavier! I don't see 0.1.0.2 on Hackage yet (but yes, do see the 0.1.0.1 you mentioned), but please do ping here when that lands and I will take care of getting this back on the Stackage nightlies. Seems like you all have the CI situation under control, I've no Nix experience but can help with multi-ghc-travice/stack setup if needs be!

**Comment by MichaelXavier** [comment]
@dalaing I actually ended up just circling back to this adding tasty-hedgehog to a project. Nightly builds are failing because tasty-hedgehog doesn't support tasty >= 0.12. Since a release that supports these is on master (0.1.0.2), is that ready to go up on hackage?

**Comment by dalaing** [comment]
I'm back in the office today (at last), so I pushed version 1.0.2 to hackage before I head off again tomorrow :)  Hopefully I'll be a bit more responsive in the future when things are less hectic :/
