### ISSUE TITLE
Support GHC-9.6

### ISSUE THREAD

**Issue by ysangkok** [qfpl/tasty-hedgehog#66]
Version 1.4.0.0 of tasty-hedgehog rejects base-4.18, which is the version shipped with GHC 9.6.1. It would be nice if this version of base was supported.

**Comment by gwils** [comment]
I've released 1.4.0.1 with support for that base version. Note that you're waiting for lifted-async and hedgehog to bump some bounds, but I built with allow-newer and there were no problems, so we should be fine once they do that.
