### ISSUE TITLE
Too strict lower bound on tasty-hedgehog in test suite

### ISSUE THREAD

**Issue by sternenseemann** [qfpl/tasty-hedgehog#70]
`tasty-hedgehog >= 1.4` is requested, but `>= 1.3` seems to work just as well which is useful when following stackage.

**Comment by gwils** [comment]
Which test suite are you talking about? This is the repository for tasty-hedgehog itself. We don't have control over other people's version bounds on our package.

**Comment by mbg** [comment]
There hasn't been an update in over a month and as `@gwils` noted, this is probably an issue with another package, so I am closing this issue for now. However, if needed, please open a new issue with more detail.

**Comment by sternenseemann** [comment]
Indeed, apologies. I guess I ended up in the wrong tab when reporting that issue back.
