### ISSUE TITLE
Document Hedgehog properties/flags that are ignored

### ISSUE THREAD

**Issue by typesanitizer** [qfpl/tasty-hedgehog#9]
After spending some time being confused why the function `Hedgehog.withTests` wasn't working, whereas the command line argument was working, I looked at the source and saw that there was a default value of 100 (presumably required by Tasty). This means that the value set inside the Hedgehog test is being ignored entirely. Instead one should tweak the option 
```
localOption (HedgehogTestLimit 1000) $ testGroup ...
```

Could this point be documented in the Readme?

Further, it seems that the `--hedgehog-verbose` flag is being ignored if the test passes... is that intentional? If yes, this should be documented too as this behaviour is opposite to that of `--quickcheck-verbose` from `tasty-quickcheck`.

Should I submit a PR addressing these two points?

**Comment by dalaing** [comment]
If you come up with a PR for these issues, I'll definitely give it a look.  Otherwise, I'll take care of it once my queue is a little smaller.

**Comment by dalaing** [comment]
It turns out that we didn't have any code for handling verbosity, so I've removed it for now.

I've also fixed the configuration handling.  Configuration parameters are left alone unless something is explicitly passed in via the command line.

Once it gets through CI I'll push a new release to Hackage.

**Comment by dalaing** [comment]
OK, there's a new version up on Hackage now that should address these issues.

Feel free to reopen this if I've missed something.

**Comment by typesanitizer** [comment]
Hi, sorry I didn't submit a PR, was busy with IRL stuff :frowning: . I should've left a comment saying that it may take me a bit of time (maybe I can add the verbosity handling ...). Will take a look at the changes, thank you!

**Comment by dalaing** [comment]
No need to be sorry, I've been pretty busy as well :)  I'm still grateful that you raised the issue.
